apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythoncluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pythoncluster
  template:
    metadata:
      labels:
        app: pythoncluster
    spec:
      containers:
        - name: pythoncontainer
          image: skafle/pythondevops:goodpythonimage
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pythonapp
spec:
  selector:
    app: pythoncluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
